title = "shellblogger configuration"

[ssh]
    user = "nole3668"
    server = "polhem.it.uu.se"
    directory = "public_html"

[site]
    author = "Noa Lerch"
    directory = "blog/public/"


# default text editor
editor = "vim"


